{
  "timestamp": "2025-02-19 12:00:45",
  "user": "dax-side",
  "error": {
    "message": "timeout of 5000ms exceeded",
    "stack": "AxiosError: timeout of 5000ms exceeded\n    at RedirectableRequest.handleRequestTimeout (/home/runner/work/Smart-Log-Error-Tracker/Smart-Log-Error-Tracker/node_modules/axios/dist/node/axios.cjs:3200:16)\n    at RedirectableRequest.emit (node:events:513:28)\n    at Timeout.<anonymous> (/home/runner/work/Smart-Log-Error-Tracker/Smart-Log-Error-Tracker/node_modules/follow-redirects/index.js:221:12)\n    at listOnTimeout (node:internal/timers:559:17)\n    at processTimers (node:internal/timers:502:7)\n    at Axios.request (/home/runner/work/Smart-Log-Error-Tracker/Smart-Log-Error-Tracker/node_modules/axios/dist/node/axios.cjs:4252:41)\n    at runNextTicks (node:internal/process/task_queues:61:5)\n    at listOnTimeout (node:internal/timers:528:9)\n    at processTimers (node:internal/timers:502:7)\n    at async LogParser.parseLogFile (/home/runner/work/Smart-Log-Error-Tracker/Smart-Log-Error-Tracker/src/logParser.js:233:24)\n    at async testNginxLogParsing (/home/runner/work/Smart-Log-Error-Tracker/Smart-Log-Error-Tracker/test/manual.test.js:22:20)"
  }
}